


[tool.ndoc]

extensions = ["py"]

format_extensions = ["py"]

ignore = [".DS_Store", ".git", ".gitignore", ".hg", ".ruff_cache", ".svn", ".venv", "__pycache__", "build", "dist", "node_modules", "out", "venv"]

[tool.pcode]

clean_extensions = ["py", "sh", "zsh"]

extensions = ["", "bash", "cfg", "cfg.py", "gitignore", "ini", "json", "md", "py", "sh", "template", "toml", "txt", "xml", "yaml", "yml", "zsh", "html", "css", "js", "ts", "webmanifest"]

format_extensions = ["py"]

ignore = [".DS_Store", ".git", ".hg", ".ruff_cache", ".svn", ".venv", "__pycache__", "venv", "release", "data", ".cache", "/web/assets/books/*"]

include = []

output_dir = "~/Documents/code.context"
